let cities = ['Albany','Troy','Schenectady','Cohoes','NYC','Poughkeepsie','Yonkers','Ossinning','New Rochelle','Buffalo','Syracuse','Rochester','Saratoga'];
let numCities = cities.length;
let randInt1 = Math.floor(Math.random()*numCities);
let randCity1 = cities[randInt1];
cities.splice(randInt1, 1);
numCities = cities.length;
let randInt2 = Math.floor(Math.random()*numCities);
let randCity2 = cities[randInt2];
console.log(randCity1,randCity2);
let times = ['1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00', '11:00', '12:00'];
let randInt3 = Math.floor(Math.random()*times.length);
let time = times[randInt3];
console.log(`Alert! a tornado warning is in effect for the following cities: ${randCity1}, ${randCity2} at ${time}`);